### ISSUE TITLE
Making the uploaded datasets compatible with Google Dataset search

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/Justice-Hub#48]
**Is your feature request related to a problem? Please describe.**
Making the datasets compatible with Google dataset search will increase the visibility of the datasets and the platform. This will also help us with the SEO of the platform. 

More details on how we can approach this can be read here - https://developers.google.com/search/docs/data-types/dataset

**Tasks**

* [x] [Explore the ckan extension](https://github.com/ckan/ckanext-dcat#structured-data-and-google-dataset-search-indexing)
* [x] [add ckanext-dcat for google dataset search](https://github.com/justicehub-in/JH-Infra/issues/7)

**Comment by curioswati** [comment]
done using the [ckan/ckanext-dcat](https://github.com/ckan/ckanext-dcat) extension. should be automated with justicehub-in/JH-Infra#7
